- path: "revature-training-project-01/data/raw/Forest_Fires.json"
  format: "csv"
  columns:
    yearr: "year"
    month: "month"
    day: "day"
    date: "date"
    state: "state"
    magnitude: "magnitude"
    injury_count: "injury_count"
    fatality_count: "fatality_count"
    latitude: "latitude"
    longitude: "longitude"
