sources:
  - path: "revature-training-project-01/data/tornado_usa.csv"
    format: "csv"
    columns:
      yr: "year"
      mo: "month"
      dy: "day"
      date: "date"
      st: "state"
      mag: "magnitude"
      inj: "injury_count"
      fat: "fatality_count"
      slat: "latitude_start"
      elat: "latitude_end"
      slon: "longitude_start"
      elon: "longitude_end"
      len: "length_miles"
      wid: "width_yards"
