- path: "revature-training-project-01/data/raw/US_Tornado_Data.csv"
  format: "csv"
  columns:
    country: "country"
    year: "year"
    month: "month"
    region: "region"
    cause: "cause"
    recorded_fires_count: "recorded_fires_count"
    burned_area_hectares: "burned_area_hectares"
    humidity_percent: "humidity_percent"
    wind_speed_kmh: "wind_speed_kmh"