- path: "data/raw/retail_store_sales.csv"
  format: "csv"
  columns:
    "Transaction ID": "transaction_id"
    "Customer ID": "customer_id"
    "Category": "category"
    "Item": "item"
    "Price Per Unit": "price_per_unit"
    "Quantity": "quantity"
    "Total Spent": "total_spent"
    "Payment Method": "payment_method"
    "Location": "location"
    "Transaction Date": "transaction_date"
    "Discount Applied": "discount_applied"
- path: "data/raw/retail_store_sales.json"
  format: "JSON"
  columns:
    "Transaction ID": "transaction_id"
    "Customer ID": "customer_id"
    "Category": "category"
    "Item": "item"
    "Price Per Unit": "price_per_unit"
    "Quantity": "quantity"
    "Total Spent": "total_spent"
    "Payment Method": "payment_method"
    "Location": "location"
    "Transaction Date": "transaction_date"
    "Discount Applied": "discount_applied"
- path: "data/raw/raw_data.json"
  format: "JSON"
  columns:
    "transaction_id": "transaction_id"
    "customer_id": "customer_id"
    "category": "category"
    "item": "item"
    "price_per_unit": "price_per_unit"
    "quantity": "quantity"
    "total_spent": "total_spent"
    "payment_method": "payment_method"
    "location": "location"
    "transaction_date": "transaction_date"
    "discount_applied": "discount_applied"
