sources:
  - format: "CSV"
    path: "data/raw/retail_store_sales.csv"
  # - type: "JSON"
  #   path: "data/raw/raw_data.json"
fields:
  count: 11
  adjacent:
    - input:
        name: "Transaction ID"
        type: "string"
      output:
        name: "transaction_id"
    - input:
        name: "Customer ID"
        type: "string"
      output:
        name: "customer_id"
    - input:
        name: "Category"
        type: "string"
      output:
        name: "category"
    - input:
        name: "Item"
        type: "string"
      output:
        name: "item"
    - input:
        name: "Price Per Unit"
        type: "float64"
      output:
        name: "price_per_unit"
    - input:
        name: "Quantity"
        type: "float64"
      output:
        name: "quantity"
    - input:
        name: "Total Spent"
        type: "float64"
      output:
        name: "total_spent"
    - input:
        name: "Payment Method"
        type: "string"
      output:
        name: "payment_method"
    - input:
        name: "Location"
        type: "string"
      output:
        name: "location"
    - input:
        name: "Transaction Date"
        type: "string"
      output:
        name: "transaction_date"
    - input:
        name: "Discount Applied"
        type: "boolean"
      output:
        name: "discount_applied"
